### PR TITLE
Made project buildable and removed unused deps

### PR DESCRIPTION
**Pull request by qrilka**
This PR intersects with #3 and #2 - I just wanted to show I went with to make the package a bit more usable in our project

### CODE REVIEW

**Comment by ocharles** [comment]
Thanks for all the issues! My guess is that I've forgotten a push, will check when I'm at my laptop tomorrow.

**Comment by qrilka** [comment]
@ocharles no updates yet?

**Comment by ocharles** [comment]
Ha, great timing! I'm just getting to this now. I've added the missing module, just fixing the other bits.

**Comment by qrilka** [comment]
@ocharles new version looks better but it still has misprint in `weight/Weight.hs` and unnecessary depencencies - do you want me to rebase this PR or you'll change this details yourself?

**Comment by qrilka** [comment]
Rebased our branch

**Comment by ocharles** [comment]
Is the removal of http-streams and io-streams correct? I can't remember if they are used by the WAI middleware or not.

**Comment by qrilka** [comment]
I don't see them used anywhere and stack build/test/bench work fine on our branch.
Actually they are the reason I started our branch as they caused our project build failure because of some SSL dependency.

**Comment by ocharles** [comment]
Cool, away they go then!

**Comment by ocharles** [comment]
I'll cut a new release soon. Thanks for all the hep and feedback.

**Comment by qrilka** [comment]
@ocharles no news when new release will land on Hackage?

**Comment by ocharles** [comment]
Sorry for the delay, I'll release shortly.

**Comment by ocharles** [comment]
Published, thanks for the nudge and sorry about a slightly slow process.

**Pull request merged**
